variable "resource_id" {
  description = "Unique ID for the resource generated by DynamoDB"
  type        = string
}

variable "resource_name" {
  description = "Name of the environment requested by the user"
  type        = string
}

variable "template_type" {
  description = "Type of template (e.g., 'static-site' or 'serverless-api')"
  type        = string
}

variable "aws_region" {
  description = "AWS Region to deploy to"
  type        = string
  default     = "us-east-1"
}
